name: Check compile
on: pull_request
jobs:
  linux-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: i686-unknown-linux-gnu
          override: true

      - name: Install g++-multilib
        run: |
          sudo apt update
          sudo apt install g++-multilib -y
      - name: Check auxmos build
        run: cargo check --target=i686-unknown-linux-gnu --release --features "all_reaction_hooks monstermos explosive_decompression"
